{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "89ad10a9-4777-4e91-a724-be0533f31214",
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import Flask, request, render_template_string\n",
    "\n",
    "app = Flask(__name__) #creating a web app\n",
    "\n",
    "class ConditionInfo: #a class to define the conditions \n",
    "    def __init__(self, name, description, cause, ingredients, tips, when_to_seek):\n",
    "        self.name = name\n",
    "        self.description = description\n",
    "        self.causes = cause\n",
    "        self.ingredients = ingredients\n",
    "        self.tips = tips\n",
    "        self.help = when_to_seek\n",
    "\n",
    "\n",
    "#conditions pulled from dataset 1 and 2\n",
    "CONDITIONS = {}\n",
    "\n",
    "def add_condition(key, name, description, cause, ingredients, tips, when_to_seek):\n",
    "    \"\"\"helper to add each condition without having to type it multiple times\"\"\"\n",
    "    CONDITIONS[key] = ConditionInfo(name=name, description=description, cause=cause, ingredients=ingredients, tips=tips, when_to_seek=when_to_seek,)\n",
    "\n",
    "#from skin_condition_knowledge_new.csv\n",
    "add_condition(key=\"cystic_acne\", name=\"Cystic acne\", description=\"Large, red, painful breakouts deep in the skin.\",cause=\"Hormonal changes, some medicines, and very inflamed clogged pores.\",ingredients=[\n",
    "\"Oral antibiotics\", \"Birth control pills\", \"Benzoyl peroxide\", \"Retinoids\", \"Isotretinoin\", \"Spironolactone\",], tips=[\"Wash face twice a day with a gentle cleanser\", \"Do not scrub or pop cysts\", \"Use non-comedogenic (non-pore-clogging) products\", \"Limit sun exposure and use sunscreen\", \"Try to reduce stress and get enough sleep\",], when_to_seek=\"See a dermatologist if cysts are painful, keep coming back, or cause scarring.\",)\n",
    "\n",
    "#blackhead condition and description\n",
    "add_condition(key=\"blackheads\", name=\"Blackheads\", description=\"Small dark spots that form when pores are clogged but stay open at the surface.\", cause=\"Oil buildup, dead skin, and clogged hair follicles.\", ingredients=[\"Salicylic acid\", \"Retinoid creams or lotions\",], tips=[\"Wash face regularly\", \"Avoid harsh scrubs and very drying products\", \"Use alcohol-free skincare\", \"Change pillowcases often\", \"Keep hair clean and off the face if oily\",], when_to_seek=\"See a dermatologist if blackheads keep coming back or worsen despite good skincare.\",)\n",
    "\n",
    "#inflammatory acne condition and description\n",
    "add_condition(key=\"inflammatory_acne\", name=\"Inflammatory acne\", description=\"Red, swollen, sore bumps that may contain pus.\",cause=\"Clogged pores and ruptured pore walls that trigger inflammation.\", ingredients=[\"Azelaic acid\", \"Benzoyl peroxide\", \"Niacinamide\", \"Retinoids (like tretinoin or adapalene)\", \"Salicylic acid\", \"Topical antibiotics\",], tips=[\"Avoid touching or picking at pimples\", \"Use non-comedogenic products\", \"Avoid harsh scrubs\", \"Gently cleanse the skin and keep a simple routine\", \"Limit very sugary foods if they seem to worsen breakouts\",], when_to_seek=\"Get help if inflammation is persistent, worsening, or if nodules/cysts form.\",)\n",
    "\n",
    "#post inflammatory hyperpigmentation condition and description\n",
    "add_condition(key=\"pih\", name=\"Post-inflammatory hyperpigmentation (PIH)\", description=\"Dark or discolored spots that appear after inflammation or injury.\", cause=\"Extra melanin made in the skin after it has been irritated or damaged.\", ingredients=[\"Hydroquinone\", \"Azelaic acid\", \"Cysteamine\", \"Vitamin C\", \"Tretinoin\", \"Corticosteroids\", \"Glycolic acid\", \"Kojic acid\",], tips=[\"Use SPF 50+ sunscreen every day on exposed areas\", \"Avoid picking or scratching spots\", \"Use gentle, non-irritating skincare\", \"Consider camouflage makeup if desired\",], when_to_seek=\"Seek help if pigmentation worsens, does not fade, or causes emotional distress.\",)\n",
    "\n",
    "#closed comedones condition and description\n",
    "add_condition(key=\"closed_comedones\", name=\"Closed comedones (whiteheads)\", description=\"Small, skin-colored bumps under the surface of the skin.\", cause=\"Extra oil, dead skin, and pore-blocking skincare or makeup.\", ingredients=[\"Salicylic acid\", \"Retinoids (tretinoin, adapalene)\", \"Azelaic acid\", \"Niacinamide\",], tips=[\"Cleanse gently twice a day\", \"Avoid heavy or oily skincare and makeup\", \"Use non-comedogenic products\", \"Introduce exfoliating products slowly to avoid irritation\",], when_to_seek=\"See a professional if comedones keep increasing, become inflamed, or do not improve.\",)\n",
    "\n",
    "#acne vulgaris condition and description\n",
    "add_condition(key=\"acne_vulgaris\", name=\"Acne vulgaris\", description=\"Common acne with blocked pores, inflammation, and breakouts.\", cause=\"Excess oil, clogged pores, bacteria, and inflammation.\", ingredients=[\"Benzoyl peroxide\", \"Salicylic acid\", \"Topical retinoids\", \"Oral antibiotics\", \"Hormonal therapy (in some cases)\"], tips=[\"Wash face twice daily with a gentle cleanser\", \"Avoid picking or squeezing pimples\", \"Use non-comedogenic makeup and skincare\", \"Keep a consistent routine and be patient\"], when_to_seek=\"See a dermatologist if acne is severe, leaves scars, or does not improve after several weeks.\")\n",
    "\n",
    "#rosacea condition and description\n",
    "add_condition(key=\"rosacea\", name=\"Rosacea\", description=\"Chronic redness on the face, sometimes with visible blood vessels or bumps.\", cause=\"Triggered by things like sun, spicy foods, alcohol, temperature changes, or stress.\", ingredients=[\"Topical metronidazole\", \"Azelaic acid\", \"Ivermectin cream\", \"Oral antibiotics for inflammation\"], tips=[\"Use gentle cleansers and moisturizers\", \"Wear sunscreen every day\", \"Avoid personal triggers like alcohol or spicy food when possible\", \"Protect skin from extreme temperatures and wind\"], when_to_seek=\"See a dermatologist if facial redness or bumps persist, worsen, or affect your quality of life.\")\n",
    "\n",
    "#sebaceous cyst condition and description\n",
    "add_condition(key=\"sebaceous_cyst\", name=\"Sebaceous cyst\", description=\"A slow-growing, usually harmless lump under the skin.\", cause=\"Blocked hair follicle or oil gland, sometimes after injury.\", ingredients=[\"Warm compresses (for comfort)\"], tips=[\"Avoid squeezing or popping the cyst\", \"Keep the area clean\", \"Use warm compresses to help drainage and reduce swelling\"], when_to_seek=\"Seek care if the cyst becomes red, painful, grows quickly, or shows signs of infection.\")\n",
    "\n",
    "#folliculitis condition and description\n",
    "add_condition(key=\"folliculitis\", name=\"Folliculitis\", description=\"Small red or pus-filled bumps around hair follicles.\", cause=\"Usually a bacterial infection, but also friction, sweat, or ingrown hairs.\", ingredients=[\"Topical antibiotics\", \"Antiseptic washes (like chlorhexidine)\", \"Oral antibiotics for widespread cases\"], tips=[\"Keep the area clean and dry\", \"Avoid tight clothing over the area\", \"Avoid shaving the irritated area until it heals\"], when_to_seek=\"See a doctor if the area is widespread, very painful, or keeps coming back.\")\n",
    "\n",
    "#milia condition and description\n",
    "add_condition(key=\"milia\", name=\"Milia\", description=\"Tiny hard white bumps under the skin where dead skin gets trapped in pores.\", cause=\"Dead skin cells trapped beneath the surface of the skin.\", ingredients=[\"Gentle exfoliation\", \"Retinoids\", \"Chemical exfoliants (AHA/BHA)\"], tips=[\"Avoid heavy creams around eyes\", \"Do not try to pop milia\", \"Use gentle exfoliating products\"], when_to_seek=\"See a dermatologist if bumps spread or do not improve.\")\n",
    "\n",
    "#eczema condition and description\n",
    "add_condition(key=\"eczema\", name=\"Eczema (Atopic Dermatitis)\", description=\"Red, itchy, dry patches on the skin that come and go.\", cause=\"Skin barrier issues that let irritants or allergens in.\", ingredients=[\"Fragrance-free moisturizers\", \"Hydrocortisone (mild steroid)\", \"Colloidal oatmeal creams\"], tips=[\"Moisturize daily\", \"Avoid hot showers\", \"Use gentle soaps\", \"Identify flare triggers\"], when_to_seek=\"Seek care if rashes are painful, widespread, or keep flaring up.\")\n",
    "\n",
    "#keratosis condition and description\n",
    "add_condition(key=\"keratosis\", name=\"Keratosis Pilaris\", description=\"Small rough bumps (like chicken skin) on arms, cheeks, or thighs.\", cause=\"A buildup of keratin blocking hair follicles.\", ingredients=[\"Lactic acid\", \"Urea cream\", \"Salicylic acid\", \"Gentle exfoliation\"], tips=[\"Moisturize after showering\", \"Avoid harsh scrubbing\", \"Use gentle chemical exfoliants\"], when_to_seek=\"See a dermatologist if bumps become very red, itchy, or painful.\")\n",
    "\n",
    "\n",
    "#writing the actual quiz questions with a dictionary with results\n",
    "\n",
    "QUESTIONS = [{\"id\": \"lesion_look\", \"text\": \"What do your CURRENT breakouts mostly look like? (Select ALL that apply)\", \"options\": {\"a\": (\"Small dark dots / blackheads\", {\"acne\": 3}), \"b\": (\"Small white/skin-colored bumps\", {\"acne\": 2, \"milia\": 2}), \"c\": (\"Red inflamed pimples\", {\"acne\": 4}), \"d\": (\"Deep painful lumps\", {\"acne\": 5}), \"e\": (\"Flat dark marks afterward\", {\"acne\": 2, \"keratosis\": 1}), \"f\": (\"General redness + bumps\", {\"rosacea\": 4})}},\n",
    "    {\"id\": \"pain_level\", \"text\": \"How painful or tender are your breakouts? (Select ALL that apply)\", \"options\": {\"a\": (\"Not painful\", {\"milia\": 2, \"keratosis\": 1}), \"b\": (\"Mild discomfort\", {\"acne\": 2}), \"c\": (\"Often very painful\", {\"acne\": 4})}},\n",
    "    {\"id\": \"location\", \"text\": \"Where do you mostly notice your skin concerns? (Select ALL that apply)\", \"options\": {\"a\": (\"Mostly T-zone\", {\"acne\": 3}), \"b\": (\"Cheeks/sides of face\", {\"rosacea\": 3, \"acne\": 1}), \"c\": (\"Face + chest/back\", {\"acne\": 4}), \"d\": (\"Scattered patches on body (arms/legs)\", {\"eczema\": 4})}},\n",
    "    {\"id\": \"after_heal\", \"text\": \"After a spot heals, what remains? (Select ALL that apply)\", \"options\": {\"a\": (\"Almost nothing\", {\"milia\": 1}), \"b\": (\"Dark marks that fade slowly\", {\"acne\": 3, \"keratosis\": 1}), \"c\": (\"Indents or raised scars\", {\"acne\": 4}), \"d\": (\"Dry, flaky patches\", {\"eczema\": 3, \"keratosis\": 1})}},\n",
    "    {\"id\": \"redness_triggers\", \"text\": \"Do you experience redness triggered by heat/spicy food/alcohol? (Select ALL that apply)\", \"options\": {\"a\": (\"Yes, I flush easily\", {\"rosacea\": 4}), \"b\": (\"Redness mostly around pimples\", {\"acne\": 2}), \"c\": (\"Redness mainly on dry/itchy patches\", {\"eczema\": 3}), \"d\": (\"Rarely any redness\", {\"milia\": 1, \"keratosis\": 1})}},\n",
    "    {\"id\": \"routine_goal\", \"text\": \"What is your MAIN skincare goal? (Select ALL that apply)\", \"options\": {\"a\": (\"Reduce painful breakouts\", {\"acne\": 4}), \"b\": (\"Clear clogged pores / texture\", {\"acne\": 3, \"milia\": 2}), \"c\": (\"Fade dark marks / spots\", {\"acne\": 2, \"keratosis\": 2}), \"d\": (\"Calm redness/sensitivity\", {\"rosacea\": 3, \"eczema\": 2}), \"e\": (\"Soothe itch / dryness\", {\"eczema\": 4})}}]\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "#this code creates the quiz page, with each question and checkboxes (so user can select multiple things) for the answers\n",
    "\n",
    "QUIZ_HTML = \"\"\"\n",
    "<h1>Skin Quiz</h1>\n",
    "<p>Select anything that applies</p>\n",
    "\n",
    "<form action=\"/result\" method=\"post\"> <!-- submit takes u to results -->\n",
    "  \n",
    "  {% for q in questions %} \n",
    "    <h3>{{ q.text }}</h3> \n",
    "\n",
    "    {% for key, opt in q.options.items() %}\n",
    "      <label>\n",
    "        <input type=\"checkbox\" name=\"{{ q.id }}\" value=\"{{ key }}\">\n",
    "        {{ opt[0] }} \n",
    "      </label><br>\n",
    "    {% endfor %}\n",
    "    <br>\n",
    "  {% endfor %}\n",
    "\n",
    "  <button type=\"submit\">submit</button>\n",
    "</form>\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "\n",
    "# This page shows the results after u press submit :D\n",
    "RESULT_HTML = \"\"\"\n",
    "<h1>You might have: {{ primary.name }}</h1>\n",
    "\n",
    "<h3>What that means</h3>\n",
    "<p>{{ primary.description }}</p>\n",
    "\n",
    "<h3>Why it can happen</h3>\n",
    "<p>{{ primary.causes }}</p>\n",
    "\n",
    "<h3>What usually helps</h3>\n",
    "<ul>\n",
    "  {% for ing in primary.ingredients %}\n",
    "    <li>{{ ing }}</li>\n",
    "  {% endfor %}\n",
    "</ul>\n",
    "\n",
    "<h3>Simple everyday things to try</h3>\n",
    "<ul>\n",
    "  {% for t in primary.tips %}\n",
    "    <li>{{ t }}</li>\n",
    "  {% endfor %}\n",
    "</ul>\n",
    "\n",
    "<h3>When to get it checked</h3>\n",
    "<p>{{ primary.help }}</p>\n",
    "\n",
    "<hr>\n",
    "\n",
    "<h2>Another possibility: {{ secondary.name }}</h2>\n",
    "<p>Skin can have more than one thing going on at the same time, so this might overlap with your main result.</p>\n",
    "\n",
    "<p>Quick description:</p>\n",
    "<p>{{ secondary.description }}</p>\n",
    "\n",
    "<br>\n",
    "<a href=\"/\">Take the quiz again</a>\n",
    "\n",
    "<p style=\"font-size:12px; color: gray; margin-top: 20px;\">\n",
    "This quiz is NOT a medical diagnosis.\n",
    "</p>\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "\n",
    "#actually giving the diagnosis\n",
    "\n",
    "def add_points_for_label(scores, label, amount):\n",
    "    \"\"\"\n",
    "    label = thing like 'acne' or 'rosacea.' basically add points to any condition which key has that word\n",
    "    \"\"\"\n",
    "    \n",
    "    for key in scores.keys():\n",
    "        if label in key:   #like acne in the term cystic_acne\n",
    "            scores[key] += amount\n",
    "\n",
    "\n",
    "\n",
    "#add the points and give first and second diagnoses\n",
    "\n",
    "@app.route(\"/\")\n",
    "def index():\n",
    "    #opening the quiz page\n",
    "    return render_template_string(QUIZ_HTML, questions=QUESTIONS)\n",
    "\n",
    "@app.route(\"/result\", methods=[\"POST\"])\n",
    "def result():\n",
    "    #start every condition at 0 points\n",
    "    scores = {key: 0 for key in CONDITIONS.keys()}\n",
    "\n",
    "    #check what the user picked for each question\n",
    "    for question in QUESTIONS:\n",
    "        selected_choices = request.form.getlist(question[\"id\"])\n",
    "\n",
    "        for choice_key in selected_choices:\n",
    "            if choice_key not in question[\"options\"]:\n",
    "                continue  #skip if user enters an option that we dont recognize or something\n",
    "\n",
    "            option_text, condition_scores = question[\"options\"][choice_key]\n",
    "\n",
    "            #total the points linked to that label\n",
    "            for label, points in condition_scores.items():\n",
    "                add_points_for_label(scores, label, points)\n",
    "\n",
    "    #figure out which conditions got the highest points\n",
    "    score_list = list(scores.items())  #taking the score dictionary and turning it into a list\n",
    "    sorted_scores = sorted(score_list, key=lambda item: item[1], reverse=True)  #having it show the diagnosis with the highest points first as the primary diagnosis\n",
    "\n",
    "\n",
    "    if not sorted_scores or sorted_scores[0][1] == 0:\n",
    "        #edge case for if user doesn't pick \n",
    "        all_keys = list(CONDITIONS.keys())\n",
    "        primary_key = all_keys[0]\n",
    "        secondary_key = all_keys[1] if len(all_keys) > 1 else all_keys[0]\n",
    "    else:\n",
    "        primary_key = sorted_scores[0][0]  #top scored for first diagnosis\n",
    "        secondary_key = sorted_scores[1][0] if len(sorted_scores) > 1 else sorted_scores[0][0]  #finding the second diagnosis\n",
    "\n",
    "    #showing the actual conditions on the page along with the treatment\n",
    "    primary_condition = CONDITIONS[primary_key]\n",
    "    secondary_condition = CONDITIONS[secondary_key]\n",
    "\n",
    "    return render_template_string(RESULT_HTML, primary=primary_condition, secondary=secondary_condition)\n",
    "\n",
    "\n",
    "#running final app\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(port=5000, debug=True, use_reloader=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ae2e9e7e-32e9-4002-86b4-007b6a001725",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
